version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  db:
    image: nouchka/sqlite3
    volumes:
      - ./db:/db
    ports:
      - "3306:3306"
